### ISSUE TITLE
base64 image not being applied to image

### ISSUE THREAD

**Issue by tunztunztunz** [coreyward/gatsby-plugin-sanity-image#5]
I'm passing all of my data into my website as _raw objects and my images are being passed to SanityImage as a full image object. They look like normal images with all the required fields and then some:

```
image:
  asset:
    metadata:
      dimensions: {_type: "sanity.imageDimensions", aspectRatio: 0.8931709265175719, height: 5008, width: 4473}
      hasAlpha: true
      isOpaque: false
      lqip: ...
      palette: {_type: "sanity.imagePalette", darkMuted: {…}, darkVibrant: {…}, dominant: {…}, lightMuted: {…}, …}
      _type: "sanity.imageMetadata"
     ...
```
I'm calling SanityImage like this: 
```
   <SanityImage {...imageAsset} className={classes} alt={alt} />
```

`imageAsset` is the image object described above.

Sanity crop and hotspot are working as expected and I think it's grabbing the correct images for each window size, but I don't see any blurring and I can't seem to find it in the markup either. This is resulting in some weird pop-in and style-shifting. 

I found a thread that suggested I needed to turn on `lqip` by creating a custom image type with `{options: metadata: ['lqip']}` but it didn't seem to change anything. I've pretty much ran down every thread and lead I can find on the internet. Any help would be very much appreciated!
